// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHnZ9Al6SUerD5Ttjb82NATiP8Vh-fCmU',
    appId: '1:215429083852:web:ae7dc8a96c9d923e560869',
    messagingSenderId: '215429083852',
    projectId: 'ai-trip-planner-d654e',
    authDomain: 'ai-trip-planner-d654e.firebaseapp.com',
    storageBucket: 'ai-trip-planner-d654e.firebasestorage.app',
    measurementId: 'G-JFKFYD6B3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2hp1_A5N8pBOMC26ZcK4tJWw9FWQc-Pk',
    appId: '1:215429083852:android:8162a3f82b6880c0560869',
    messagingSenderId: '215429083852',
    projectId: 'ai-trip-planner-d654e',
    storageBucket: 'ai-trip-planner-d654e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRbCTY6CcKjbISRuWi5CZWxb5qUN7aYEw',
    appId: '1:215429083852:ios:12cb4be1b424b9ea560869',
    messagingSenderId: '215429083852',
    projectId: 'ai-trip-planner-d654e',
    storageBucket: 'ai-trip-planner-d654e.firebasestorage.app',
    iosBundleId: 'com.example.aiTripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRbCTY6CcKjbISRuWi5CZWxb5qUN7aYEw',
    appId: '1:215429083852:ios:12cb4be1b424b9ea560869',
    messagingSenderId: '215429083852',
    projectId: 'ai-trip-planner-d654e',
    storageBucket: 'ai-trip-planner-d654e.firebasestorage.app',
    iosBundleId: 'com.example.aiTripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHnZ9Al6SUerD5Ttjb82NATiP8Vh-fCmU',
    appId: '1:215429083852:web:7c9c4d97071d7980560869',
    messagingSenderId: '215429083852',
    projectId: 'ai-trip-planner-d654e',
    authDomain: 'ai-trip-planner-d654e.firebaseapp.com',
    storageBucket: 'ai-trip-planner-d654e.firebasestorage.app',
    measurementId: 'G-KQXDW08CSP',
  );

}